const assert = require("assert");
const fs = require("fs");
const path = require("path");
const core = require("../site/src/governance-core");

const root = path.join(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

const html = read("site/index.html");
const css = read("site/styles.css");
const app = read("site/src/app.js");
const dilemmas = read("site/src/dilemmas.js");
const siteApi = read("app/siteApi.ts");
const privateDaoClient = read("app/privateDaoClient.ts");
const devServer = read("scripts/dev-server.js");
const vercelConfig = read("vercel.json");
const vercelIgnore = read(".vercelignore");
const vercelApi = read("api/index.js");
const packageJson = read("package.json");
const supabaseSchema = read("supabase/schema.sql");
const sdGenerator = read("scripts/sd-webui-generator.js");
const windowsGeneratorCmd = read("scripts/start-windows-image-generator.cmd");
const localImageDocs = read("docs/local-image-generator.md");
const deploymentDocs = read("docs/deployment.md");
const windowsGpuDocs = read("docs/windows-gpu-mac-dao.md");
const program = read("programs/private_dao/src/lib.rs");
const encryptedIx = read("encrypted-ixs/private_vote.rs");

assert(html.includes("Would You DAO?"), "site title should be present");
assert(html.includes("sock-logo.png"), "custom sock logo should be mounted");
assert(html.includes("data-topbar-new-vote"), "connected users should get a topbar new vote action");
assert(html.includes("data-about-open"), "topbar should include an about action");
assert(html.includes("data-about-dialog"), "site should include an Arcium about dialog");
assert(html.includes('name="optionA"'), "custom round form should expose one option A input");
assert(html.includes('name="optionB"'), "custom round form should expose one option B input");
assert(!html.includes("optionAEn"), "custom round form should not require separate English fields");
assert(!html.includes("optionAKo"), "custom round form should not require separate Korean fields");
assert(html.includes("data-vote-feed"), "scroll-sensitive vote feed should exist");
assert(html.includes("dao-girl-cutout.png"), "feed mascot cutout should be mounted");
assert(html.includes('data-tab="hot"'), "hot bottom tab should exist");
assert(html.includes('data-tab="new"'), "new bottom tab should exist");
assert(html.includes('data-tab="profile"'), "profile bottom tab should exist");
assert(html.includes("data-lang"), "language selector should exist");
assert(html.includes("src/dilemmas.js"), "dilemma bank should load");
assert(dilemmas.includes("머리 5일 안 감고 몸은 매일 씻기"), "dilemma bank should include provided hygiene examples");
assert(dilemmas.includes("카톡 답장 10분 안에 무조건 해야 함"), "dilemma bank should include provided daily-life examples");
assert(dilemmas.includes("평생 치킨 못 먹기"), "dilemma bank should include provided food examples");
assert(dilemmas.includes("Get $100,000 right now"), "English money dilemmas should convert won amounts to dollars");
assert(dilemmas.includes("Receive a random $5,000 deposit once a month"), "English money dilemmas should format converted dollar amounts");
assert(!dilemmas.includes("100 million won"), "English money dilemmas should not display won amounts");
assert(dilemmas.includes("친구랑 여행 갔는데 계획이 너무 빡셈"), "dilemma bank should include expanded friends examples");
assert(dilemmas.includes("데이트 비용 반반 확실한 사람"), "dilemma bank should include expanded dating examples");
assert(dilemmas.includes("회의가 많지만 짧음"), "dilemma bank should include expanded school-work examples");
assert(dilemmas.includes("내 생각이 자막으로 보임"), "dilemma bank should include provided absurd examples");
assert(css.includes("scroll-snap-type"), "feed should use scroll snapping");
assert(css.includes(".bottom-nav"), "bottom navigation styles should exist");
assert(css.includes(".logo-mark img"), "custom logo image should fit inside the topbar mark");
assert(css.includes(".topbar-right"), "topbar should group about and wallet actions");
assert(css.includes(".about-point"), "about dialog should have structured privacy/proof copy");
assert(css.includes(".new-vote-button[hidden]"), "topbar new vote action should hide before wallet connect");
assert(css.includes(".vote-card"), "single-vote card styles should exist");
assert(css.includes(".card-main"), "vote card content should be vertically centered");
assert(css.includes(".category-filter-row"), "vote card should expose category filter controls");
assert(css.includes(".category-filter-row button.is-active"), "active category filter should have an on state");
assert(css.includes("cursor: grab"), "category filter should be draggable with a mouse");
assert(css.includes(".choice-headline"), "category and status should align with the prompt pill");
assert(css.includes(".feed-mascot"), "feed mascot should be positioned as a decorative cutout");
assert(css.includes("transform 320ms"), "feed should page cards with transform animation");
assert(app.includes("scrollCooldownUntil"), "feed scroll should throttle accepted card changes");
assert(app.includes("topbarNewVote.hidden = !state.wallet"), "topbar new vote action should show after wallet connect");
assert(app.includes("Why Arcium?"), "app copy should explain why Arcium is useful");
assert(app.includes("Absurd questions. Serious privacy."), "about copy should balance funny topic with professional privacy framing");
assert(app.includes("aboutDialog.showModal()"), "about action should open the Arcium explanation dialog");
assert(app.includes("Server returned a non-JSON response"), "API helper should avoid raw JSON parse errors on Vercel timeout pages");
assert(app.includes("voteQueued"), "vote UX should handle serverless Arcium finalization timeouts");
assert(app.includes("resultQueued"), "reveal UX should handle serverless Arcium finalization timeouts");
assert(app.includes("connectedWalletAction"), "profile wallet action should change copy after connect");
assert(app.includes("els.profileConnect.disabled = Boolean(state.wallet)"), "profile connect action should disable after wallet connect");
assert(app.includes("HANGUL_PATTERN"), "custom round submission should detect Korean input");
assert(app.includes("localizeOptions"), "custom round submission should automatically save both languages");
assert(app.includes("normalizeEnglishWonAmounts"), "custom round English translations should normalize won amounts to dollars");
assert(app.includes("normalizeEnglishPerspective"), "custom round English text should normalize first-person possessives");
assert(app.includes('.replace(/\\bmy\\b/g, "your")'), "English card text should convert my to your");
assert(!app.includes("data-auto-translate"), "custom round submission should not depend on a separate translate button");
assert(app.includes("wheelGestureLocked"), "wheel input should advance once per gesture");
assert(app.includes("wheelCardIndex"), "wheel momentum should be tied to the source card");
assert(app.includes("categoryFilters"), "feed should support multi-category filtering");
assert(app.includes("data-category-filter"), "category labels should be clickable filters");
assert(app.includes("toggleCategoryFilter"), "category labels should toggle without forcing a single category");
assert(app.includes('hotTab: "Finalized"'), "first tab should be labeled Finalized");
assert(app.includes('return state.view === "new" ? !proposal.finalized && !isClosed(proposal) : proposal.finalized'), "new tab should only show active broadcasts and finalized tab should only show final rounds");
assert(app.includes('if (state.view === "new") return b.createdAt - a.createdAt'), "new tab should show launched rounds by newest first");
assert(!app.includes("data-launch-dilemma"), "question feed should not expose template launch buttons");
assert(app.includes("handleCategoryPointerDown"), "category filter should support pointer dragging");
assert(app.includes('"hygiene", "daily", "food"'), "category filter should put hygiene near the front");
assert(app.includes("visibleVoteCount"), "new broadcasts should show vote counts without ratios");
assert(app.includes("materializeSeedProposal"), "seed broadcasts should launch real on-chain rounds before voting");
assert(app.includes("launchingSeed"), "seed round votes should explain the initial on-chain launch step");
assert(app.includes("data-skip-next"), "skip action should advance to the next vote instead of submitting a transaction");
assert(app.includes("skipToNextCard"), "skip action should page the feed locally");
assert(!app.includes('submitVote("abstain"'), "skip action should not submit an abstain transaction");
assert(app.includes('choiceCard("a", "A", text(meta.optionA)'), "proposal option A text should render inside its card");
assert(app.includes("choiceStage(text(meta.prompt), meta.categoryId"), "proposal prompt should render with category and status metadata");
assert(!app.includes("choice-placeholder.png"), "feed should not render image placeholders");
assert(!app.includes("choice-image-box"), "feed should not render generated image boxes");
assert(!app.includes("privacy-note"), "feed cards should not show privacy note copy");
assert(!app.includes("No one sees the result"), "removed privacy note text should stay out of the app bundle");
assert(css.includes("grid-template-columns: repeat(2, minmax(0, 1fr))"), "option cards should stay side by side");
assert(css.includes(".choice-stage {\n  display: grid;\n  width: 100%;"), "choice stage should match option card width");
assert(!css.includes(".choice-image"), "site CSS should not include image choice boxes");
assert(css.includes(".choice-button em"), "choice cards should include compact action labels");
assert(css.includes("hyphens: none"), "choice card text should not split words with automatic hyphens");
assert(siteApi.includes("REMOTE_IMAGE_GENERATOR_URL"), "server should support a remote image generator");
assert(siteApi.includes("ENABLE_IMAGE_GENERATION"), "server should keep image generation opt-in");
assert(siteApi.includes("generatedImageUrl"), "remote image paths should normalize to browser-usable URLs");
assert(siteApi.includes("IMAGE_GENERATOR_TOKEN"), "server should support authenticated image generator calls");
assert(siteApi.includes("IMAGE_GENERATION_SIZE"), "server should support smaller generated image sizes");
assert(siteApi.includes("optionPromptHints"), "server should enrich short choices into clearer image prompts");
assert(siteApi.includes("fully clothed cute chibi-style Korean female character"), "image prompts should default to a chibi female character scene");
assert(siteApi.includes("no duplicate characters"), "image prompts should reject duplicated character sheets");
assert(siteApi.includes("fried chicken"), "image prompts should add concrete food props");
assert(siteApi.includes("translateRoundOptions"), "server should proxy local translation requests");
assert(siteApi.includes("DEEPL_API_KEY"), "server should support DeepL translation through an environment variable");
assert(siteApi.includes("api-free.deepl.com"), "DeepL Free keys should use the free API endpoint");
assert(siteApi.includes("process.env.VERCEL"), "server should use Vercel-safe defaults in serverless deployments");
assert(siteApi.includes("KEYPAIR_JSON"), "server should support JSON keypairs for serverless deployments");
assert(siteApi.includes("KEYPAIR_BASE64"), "server should support base64 keypairs for serverless deployments");
assert(siteApi.includes("SUPABASE_URL"), "server should support Supabase metadata storage");
assert(siteApi.includes("SUPABASE_SERVICE_ROLE_KEY"), "server should use a server-side Supabase key");
assert(siteApi.includes("DATABASE_URL"), "server should support direct Supabase Postgres URLs");
assert(siteApi.includes("readStateFromPostgres"), "server should read metadata from Postgres when configured");
assert(siteApi.includes("writeStateToPostgres"), "server should write metadata to Postgres when configured");
assert(siteApi.includes("waitForFinalizationOrPending"), "serverless vote confirmation should return JSON before Vercel timeouts");
assert(siteApi.includes("ARCIUM_FINALIZATION_WAIT_MS"), "finalization wait should be configurable");
assert(siteApi.includes("materializedSlugs"), "seeded demo rounds should disappear after they are launched on-chain");
assert(siteApi.includes("finalizationStatus: finalization.status"), "proposal confirmation should report pending Arcium initialization");
assert(siteApi.includes("metadataStorageMode"), "status should report the active metadata storage mode");
assert(siteApi.includes("writeStateToSupabase"), "server should persist metadata to Supabase when configured");
assert(siteApi.includes("persistentState"), "server should not persist regenerated demo rounds as durable metadata");
assert(siteApi.includes("record.total ?? yes + no + abstain"), "status fallback should preserve local demo tally counts");
assert(siteApi.includes("readDilemmaBank"), "server should seed launched demo rounds from the question bank");
assert(siteApi.includes("HOT_DEMO_TALLIES"), "server should keep hot demo rounds separate from low-count new rounds");
assert(siteApi.includes("WEEKLY_DEMO_BATCH_SIZE = 10"), "server should rotate ten new demo broadcasts per week");
assert(siteApi.includes("DEMO_WEEK_SECONDS"), "server should give weekly demo broadcasts a one-week window");
assert(devServer.includes("process.env.HOST"), "web server should support deploy-time host binding");
assert(devServer.includes('"/api/translate"'), "web server should expose translation API route");
assert(devServer.includes('".png": "image/png"'), "dev server should serve generated PNGs with an image content type");
assert(privateDaoClient.includes("Keypair.generate()"), "serverless deployments should not require a local keypair file for read-only status");
assert(privateDaoClient.includes('startsWith("base64:")'), "keypair loader should support base64 encoded secrets");
assert(vercelConfig.includes('"/api/(.*)"'), "Vercel config should route API requests to the serverless handler");
assert(vercelConfig.includes('"/site/index.html"'), "Vercel config should serve the mobile app entrypoint");
assert(vercelConfig.includes("app/**"), "Vercel function should include TypeScript API modules");
assert(vercelConfig.includes("site/src/dilemmas.js"), "Vercel function should include the seeded dilemma bank");
assert(vercelIgnore.includes(".env"), "Vercel deploy should exclude local environment secrets");
assert(vercelIgnore.includes(".anchor"), "Vercel deploy should exclude local Anchor test ledgers");
assert(vercelIgnore.includes("/*.zip"), "Vercel deploy should exclude handoff archives");
assert(vercelIgnore.includes("/site/generated"), "Vercel deploy should exclude local generated images");
assert(vercelApi.includes("tsx/cjs"), "Vercel API should load TypeScript server modules");
assert(vercelApi.includes('"/api/wallet/proposal-tx"'), "Vercel API should expose connected-wallet proposal transaction route");
assert(packageJson.includes('"deploy:vercel"'), "package script should expose Vercel deployment");
assert(packageJson.includes('"pg"'), "package should include node-postgres for Supabase pooler storage");
assert(supabaseSchema.includes("create table if not exists public.would_you_dao_state"), "Supabase schema should create the metadata state table");
assert(supabaseSchema.includes("enable row level security"), "Supabase schema should enable RLS");
assert(deploymentDocs.includes("Supabase Metadata Store"), "deployment docs should explain the Supabase metadata role");
assert(packageJson.includes('"image:sd-webui"'), "package script should run the local SD WebUI bridge");
assert(sdGenerator.includes("/sdapi/v1/txt2img"), "local image bridge should call Stable Diffusion WebUI txt2img");
assert(sdGenerator.includes("IMAGE_GENERATOR_TOKEN"), "local image bridge should support token auth");
assert(sdGenerator.includes("USE_LOCAL_LLM_PROMPTS"), "local image bridge should document optional Ollama prompt rewriting");
assert(sdGenerator.includes("PINATA_JWT"), "local image bridge should support optional Pinata IPFS uploads");
assert(sdGenerator.includes("chibi-style Korean female character"), "local image bridge should default to chibi female character prompts");
assert(sdGenerator.includes("character sheet"), "local image bridge should reject character-sheet outputs");
assert(sdGenerator.includes("white blob"), "local image bridge should reject blank blob generations");
assert(sdGenerator.includes('url.pathname !== "/translate"'), "local image bridge should expose Ollama translation");
assert(windowsGeneratorCmd.includes("IMAGE_GENERATION_SIZE=384"), "Windows generator script should default to smaller images");
assert(localImageDocs.includes("IMAGE_GENERATION_SIZE=512"), "local image docs should describe smaller image generation");
assert(windowsGpuDocs.includes("Windows GPU + Mac DAO Setup"), "Windows/Mac image generator runbook should exist");
assert(deploymentDocs.includes("HOST=0.0.0.0"), "deployment docs should cover platform host binding");
assert(app.includes('addEventListener("touchmove", handleTouchMove, { passive: false })'), "touch movement should be cancelable");
assert(program.includes("#[arcium_program]"), "Solana program should use Arcium macro");
assert(program.includes("verify_output"), "callbacks should verify Arcium output");
assert(encryptedIx.includes("Enc<Mxe, BallotState>"), "encrypted shared state should be MXE-owned");
assert(encryptedIx.includes("init_private_ballot"), "private ballot initialization should exist");
assert(encryptedIx.includes("publish_private_tally"), "final tally instruction should exist");

const receipts = [
  core.makeEncryptedReceipt({ proposalId: "p", wallet: "a", choice: "yes", round: 0 }),
  core.makeEncryptedReceipt({ proposalId: "p", wallet: "b", choice: "no", round: 1 }),
  core.makeEncryptedReceipt({ proposalId: "p", wallet: "c", choice: "yes", round: 2 }),
  core.makeEncryptedReceipt({ proposalId: "p", wallet: "d", choice: "abstain", round: 3 })
];

const tally = core.tallyVotes(receipts);
assert.deepStrictEqual(tally, { yes: 2, no: 1, abstain: 1, total: 4 });
assert(core.createProofId("p", receipts, tally).startsWith("proof_"));

console.log("Would You DAO smoke checks passed");
